services:
  postgres:
    image: postgres:16
    container_name: clocktrack-postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: clocktrack
      POSTGRES_PASSWORD: clocktrack
      POSTGRES_DB: clocktrack
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
